-- ═══════════════════════════════════════════════════════════
-- 017 — Web push for the iPhone home-screen app
--
-- The Android app schedules its own reminders and polls the feed.
-- A home-screen web app can't do either, so the server sends them
-- as Web Push (iOS 16.4+, once the app is on the home screen):
--   push_subscriptions  one row per device that turned notifications on,
--                       with that device's reminder preferences;
--   push_sent           keys of reminders already sent, so a reminder
--                       goes out once however often the job runs;
--   app_secrets         the VAPID key pair (generated by the server on
--                       first use) and the scheduler's key.
-- The scheduler is pg_cron calling /api/cron/reminders every five
-- minutes through pg_net. If either extension is unavailable the
-- tables are still created and team updates still push instantly;
-- only the timed reminders wait for the scheduler.
-- ═══════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS push_subscriptions (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,
  endpoint    TEXT NOT NULL UNIQUE,
  p256dh      TEXT NOT NULL,
  auth        TEXT NOT NULL,
  prefs       JSONB NOT NULL DEFAULT '{}'::jsonb,
  user_agent  TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_ok_at  TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS push_subscriptions_user ON push_subscriptions (user_id);
ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS push_sent (
  key      TEXT PRIMARY KEY,
  sent_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE push_sent ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS app_secrets (
  key         TEXT PRIMARY KEY,
  value       TEXT NOT NULL,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE app_secrets ENABLE ROW LEVEL SECURITY;

INSERT INTO app_secrets (key, value)
VALUES ('reminders_cron_key', replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', ''))
ON CONFLICT (key) DO NOTHING;

DO $$
BEGIN
  CREATE EXTENSION IF NOT EXISTS pg_net;
  CREATE EXTENSION IF NOT EXISTS pg_cron;
  PERFORM cron.unschedule(jobid) FROM cron.job WHERE jobname = 'bhumi-reminders';
  PERFORM cron.schedule(
    'bhumi-reminders',
    '*/5 * * * *',
    $cmd$
      SELECT net.http_get(
        url := 'https://www.bhumiestates.in/api/cron/reminders',
        headers := jsonb_build_object('x-cron-key', (SELECT value FROM public.app_secrets WHERE key = 'reminders_cron_key'))
      )
    $cmd$
  );
EXCEPTION WHEN others THEN
  RAISE NOTICE 'Reminder scheduler not set up: %', SQLERRM;
END $$;
